Style/WordArray:
  Description: 'Use %w or %W for an array of words. (https://rubystyle.guide#percent-w)'
  Enabled : false

Layout/ArgumentAlignment:
  Description: 'check if the arguments on a multi-line method definition are aligned. (https://rubystyle.guide#no-double-indent)'
  Enabled : true
  EnforcedStyle: with_fixed_indentation

Style/TrailingCommaInHashLiteral:
  Description: 'https://docs.rubocop.org/rubocop/cops_style.html#styletrailingcommainhashliteral'
  Enabled: true
  EnforcedStyleForMultiline: no_comma
