name: Test the Baseline

on: [push, pull_request]

jobs:

  container:
    runs-on: ubuntu-latest
    container: chef/chefworkstation
    steps:
      - name: Configure AWS credentials
        env:
          AWS_SG_ID: ${{ secrets.AWS_SG_ID }}
          AWS_SUBNET_ID: ${{ secrets.AWS_SUBNET_ID }}
          AWS_SSH_KEY_ID: ${{ secrets.AWS_SSH_KEY_ID }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Echo our env
        run: echo $AWS_SSH_KEY_ID
        run: echo $AWS_REGION
        run: env
        
      - name: Setup our ssh-key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/${{ secrets.AWS_SSH_KEY_ID }}.pem
          chmod 400 ~/.ssh/${{ secrets.AWS_SSH_KEY_ID }}.pem
          ls -alh ~/.ssh/${{ secrets.AWS_SSH_KEY_ID }}.pem
        
#       - name: Check out repository
#         uses: actions/checkout@v2
#       - name: Get InSpec Version
#         run: CHEF_LICENSE=accept inspec -v
#       - name: Check the profile
#         run: CHEF_LICENSE=accept inspec check .
